// TASK-001-004: /.well-known/security.txt (RFC 9116)
// TASK-001-007: POST /api/accounts/delete-gdpr — GDPR erasure initiation
// TASK-001-009: GET  /api/accounts/export-data — GDPR data portability (Art. 20)
// TASK-001-011: GET  /api/compliance/evidence   — Compliance evidence API
// TASK-001-012: CSV export via generate_csv_report()
// TASK-001-013: Routes registered here and mounted in main.rs

use chrono::{TimeDelta, Utc};
use rocket::{get, post, routes, Route};
use rocket::serde::json::Json;
use serde_json::Value;

use crate::{
    api::{admin::AdminToken, ApiResult, EmptyResult, JsonResult},
    auth::Headers,
    db::{
        models::{Cipher, ErasureLog, Send, TwoFactor, User},
        DbConn,
    },
    CONFIG,
};

pub fn routes() -> Vec<Route> {
    routes![
        security_txt,
        delete_account_gdpr,
        export_user_data,
        get_compliance_evidence,
        export_compliance_report,
    ]
}

// ═══════════════════════════════════════════════════════════════════════════════
// TASK-001-004: /.well-known/security.txt
// ═══════════════════════════════════════════════════════════════════════════════

/// RFC 9116 security.txt
/// Served at `GET /.well-known/security.txt` — no auth required.
#[get("/.well-known/security.txt")]
pub fn security_txt() -> (rocket::http::ContentType, String) {
    let contact = CONFIG.security_txt_contact();
    let expires = CONFIG.security_txt_expires();

    let content = if contact.is_empty() {
        // Minimal valid security.txt when not configured
        format!(
            "# security.txt generated by Vaultwarden (SOL-001)\n\
             # Configure SECURITY_TXT_CONTACT and SECURITY_TXT_EXPIRES environment variables.\n\
             Expires: {}\n",
            // Provide a sane default 1 year ahead
            (Utc::now() + TimeDelta::try_days(365).unwrap())
                .format("%Y-%m-%dT%H:%M:%SZ")
        )
    } else {
        let expires_str = if expires.is_empty() {
            (Utc::now() + TimeDelta::try_days(365).unwrap())
                .format("%Y-%m-%dT%H:%M:%SZ")
                .to_string()
        } else {
            expires.clone()
        };
        format!(
            "Contact: {contact}\n\
             Expires: {expires_str}\n\
             Preferred-Languages: en\n\
             # Generated by Vaultwarden (SOL-001 Enterprise Compliance Framework)\n"
        )
    };

    (rocket::http::ContentType::Plain, content)
}

// ═══════════════════════════════════════════════════════════════════════════════
// TASK-001-007: GDPR Erasure Initiation
// ═══════════════════════════════════════════════════════════════════════════════

/// `POST /api/accounts/delete-gdpr`
///
/// Initiates the GDPR erasure pipeline for the authenticated user:
/// 1. Revokes all active sessions (invalidates security stamp).
/// 2. Schedules PII erasure date = now + GDPR_ERASURE_DELAY_DAYS.
/// 3. Creates an ErasureLog entry in the append-only audit chain.
/// 4. Marks user as pending erasure in the users table.
#[post("/api/accounts/delete-gdpr")]
pub async fn delete_account_gdpr(headers: Headers, conn: DbConn) -> EmptyResult {
    let mut user = headers.user;
    let ip = headers.ip.ip.to_string();

    // Guard: disallow if already scheduled
    if user.pii_erasure_scheduled_at.is_some() {
        err!("GDPR erasure is already scheduled for this account");
    }

    let delay_days = CONFIG.gdpr_erasure_delay_days() as i64;
    let scheduled_at = (Utc::now() + TimeDelta::try_days(delay_days).unwrap()).naive_utc();

    // Revoke all sessions by rotating the security stamp
    user.reset_security_stamp();
    user.pii_erasure_scheduled_at = Some(scheduled_at);
    user.save(&conn).await?;

    // Append to erasure audit chain
    let prev_hash = ErasureLog::get_last_hash(&conn).await;
    let log = ErasureLog::new(&user.uuid.to_string(), scheduled_at, &ip, &prev_hash);
    log.save(&conn).await?;

    info!("[GDPR] Erasure scheduled for user {} at {scheduled_at}", user.uuid);
    Ok(())
}

// ═══════════════════════════════════════════════════════════════════════════════
// TASK-001-009: GDPR Data Export (Art. 20 — Data Portability)
// ═══════════════════════════════════════════════════════════════════════════════

/// `GET /api/accounts/export-data`
///
/// Returns all personal data held for the authenticated user as JSON.
/// Complies with GDPR Article 20 (right to data portability).
#[get("/api/accounts/export-data")]
pub async fn export_user_data(headers: Headers, conn: DbConn) -> JsonResult {
    let user = &headers.user;
    let user_uuid = &user.uuid;

    // Collect ciphers (async to_json)
    let raw_ciphers = Cipher::find_owned_by_user(user_uuid, &conn).await;
    let mut ciphers: Vec<Value> = Vec::with_capacity(raw_ciphers.len());
    for c in &raw_ciphers {
        ciphers.push(c.to_json(&headers.host, user_uuid, None, crate::api::core::ciphers::CipherSyncType::User, &conn).await?);
    }

    // Collect sends
    let sends: Vec<Value> = Send::find_by_user(user_uuid, &conn)
        .await
        .iter()
        .map(|s| s.to_json())
        .collect();

    // Collect 2FA config (types only — no secrets)
    let two_factors: Vec<Value> = TwoFactor::find_by_user(user_uuid, &conn)
        .await
        .iter()
        .map(|t| {
            json!({
                "type": t.atype,
                "enabled": t.enabled,
            })
        })
        .collect();

    Ok(Json(json!({
        "object": "gdprDataExport",
        "profile": {
            "id": user.uuid,
            "name": user.name,
            "email": user.email,
            "createdAt": user.created_at,
            "updatedAt": user.updated_at,
            "verifiedAt": user.verified_at,
        },
        "ciphers": ciphers,
        "sends": sends,
        "twoFactorProviders": two_factors,
        "exportedAt": Utc::now(),
    })))
}

// ═══════════════════════════════════════════════════════════════════════════════
// TASK-001-010/011/012: Compliance Evidence API (Admin-only)
// ═══════════════════════════════════════════════════════════════════════════════

/// `GET /api/compliance/evidence?standard=pci-dss|soc2|iso27001|gdpr`
///
/// Returns structured compliance evidence for the requested standard.
/// Requires admin authentication and `COMPLIANCE_REPORT_ENABLED=true`.
#[get("/api/compliance/evidence?<standard>")]
pub async fn get_compliance_evidence(
    _admin: AdminToken,
    standard: Option<String>,
    conn: DbConn,
) -> JsonResult {
    if !CONFIG.compliance_report_enabled() {
        err!("Compliance reports are disabled. Set COMPLIANCE_REPORT_ENABLED=true.");
    }

    let std_name = standard.as_deref().unwrap_or("all");
    let evidence = collect_evidence(std_name, &conn).await;

    Ok(Json(evidence))
}

/// `GET /api/compliance/evidence/export?format=json|csv`
///
/// Exports compliance evidence. JSON by default; CSV when format=csv.
/// TASK-001-012: CSV generation via generate_csv_report().
#[get("/api/compliance/evidence/export?<format>&<standard>")]
pub async fn export_compliance_report(
    _admin: AdminToken,
    format: Option<String>,
    standard: Option<String>,
    conn: DbConn,
) -> ApiResult<(rocket::http::ContentType, String)> {
    if !CONFIG.compliance_report_enabled() {
        err!("Compliance reports are disabled.");
    }

    let std_name = standard.as_deref().unwrap_or("all");
    let evidence = collect_evidence(std_name, &conn).await;

    match format.as_deref() {
        Some("csv") => Ok((
            rocket::http::ContentType::new("text", "csv"),
            generate_csv_report(&evidence),
        )),
        _ => Ok((
            rocket::http::ContentType::JSON,
            serde_json::to_string_pretty(&evidence).unwrap_or_default(),
        )),
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// TASK-001-010: Evidence collectors
// ═══════════════════════════════════════════════════════════════════════════════

/// Collect compliance evidence for the specified standard (or all).
async fn collect_evidence(standard: &str, conn: &DbConn) -> Value {
    // Common stats
    let total_users = User::count_all(conn).await;
    let users_with_2fa = TwoFactor::count_distinct_users(conn).await;
    let tfa_rate = if total_users > 0 {
        (users_with_2fa as f64 / total_users as f64 * 100.0).round() as i64
    } else {
        0
    };
    let completed_erasures = ErasureLog::count_completed(conn).await;

    let base = json!({
        "generatedAt": Utc::now(),
        "region": CONFIG.data_residency_region(),
        "totalUsers": total_users,
        "twoFactorRate": tfa_rate,
        "completedGdprErasures": completed_erasures,
        "vaultwardenVersion": env!("CARGO_PKG_VERSION"),
    });

    match standard {
        "pci-dss" => json!({
            "standard": "PCI-DSS v4.0",
            "evidence": {
                "requirement_2_2": "Security headers enforced via SecurityHeadersFairing",
                "requirement_6_3": format!("2FA rate: {}%", tfa_rate),
                "requirement_10_3": "Audit events stored in `event` table with immutable timestamps",
                "dataStats": base,
            }
        }),
        "soc2" => json!({
            "standard": "SOC 2 Type II",
            "evidence": {
                "CC6_1": format!("Access controls: 2FA rate {}%", tfa_rate),
                "CC6_6": "Trusted proxy validation via get_real_ip()",
                "CC7_2": "Emergency access with multi-tier notifications",
                "A1_1": format!("Data region: {}", CONFIG.data_residency_region()),
                "dataStats": base,
            }
        }),
        "iso27001" => json!({
            "standard": "ISO 27001:2022",
            "evidence": {
                "A_5_23": "Information security in use of cloud services",
                "A_8_5": format!("Privileged access rate (2FA): {}%", tfa_rate),
                "A_8_24": "Cryptographic controls: AES-256-GCM, RSA-2048",
                "A_8_32": "Change log: see /admin panel event log",
                "dataStats": base,
            }
        }),
        "gdpr" => json!({
            "standard": "GDPR",
            "evidence": {
                "article_17": format!("Right to erasure: {} completed erasures", completed_erasures),
                "article_20": "Data portability: GET /api/accounts/export-data",
                "article_32": "Technical security: TLS, PBKDF2/Argon2, E2E encryption",
                "dataStats": base,
            }
        }),
        _ => json!({
            "standard": "all",
            "evidence": {
                "pciDss": collect_pci_summary(tfa_rate),
                "soc2": collect_soc2_summary(tfa_rate),
                "iso27001": collect_iso27001_summary(tfa_rate),
                "gdpr": collect_gdpr_summary(completed_erasures),
                "dataStats": base,
            }
        }),
    }
}

fn collect_pci_summary(tfa_rate: i64) -> Value {
    json!({ "twoFactorRate": tfa_rate, "encryptionAlgorithm": "AES-256-GCM" })
}

fn collect_soc2_summary(tfa_rate: i64) -> Value {
    json!({ "twoFactorRate": tfa_rate, "trustedProxyValidation": true })
}

fn collect_iso27001_summary(tfa_rate: i64) -> Value {
    json!({ "privilegedAccessRate": tfa_rate, "keyManagement": "RSA-2048 + AES-256-GCM" })
}

fn collect_gdpr_summary(completed_erasures: i64) -> Value {
    json!({ "completedErasures": completed_erasures, "portabilityEndpoint": "/api/accounts/export-data" })
}

// ═══════════════════════════════════════════════════════════════════════════════
// TASK-001-012: CSV report generation (report.rs inline)
// ═══════════════════════════════════════════════════════════════════════════════

/// Generate a CSV compliance report from evidence JSON.
/// Flattens the top-level `evidence` object into key,value rows.
pub fn generate_csv_report(evidence: &Value) -> String {
    let mut out = String::from("field,value\n");

    if let Some(obj) = evidence.as_object() {
        flatten_into_csv(obj, "", &mut out);
    }

    out
}

fn flatten_into_csv(obj: &serde_json::Map<String, Value>, prefix: &str, out: &mut String) {
    for (key, value) in obj {
        let full_key = if prefix.is_empty() {
            key.clone()
        } else {
            format!("{prefix}.{key}")
        };

        match value {
            Value::Object(inner) => flatten_into_csv(inner, &full_key, out),
            Value::String(s) => out.push_str(&format!("{full_key},{}\n", csv_escape(s))),
            other => out.push_str(&format!("{full_key},{}\n", csv_escape(&other.to_string()))),
        }
    }
}

fn csv_escape(s: &str) -> String {
    if s.contains(',') || s.contains('"') || s.contains('\n') {
        format!("\"{}\"", s.replace('"', "\"\""))
    } else {
        s.to_string()
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// TASK-001-008: Background job — execute_scheduled_erasures
// Called from main.rs scheduler (wired in TASK-001-013).
// ═══════════════════════════════════════════════════════════════════════════════

/// Daily background job: finds users past their `pii_erasure_scheduled_at`
/// deadline and anonymises their PII fields (GDPR right to erasure).
///
/// Anonymisation strategy:
/// - `email`  → `erased-{uuid}@erased.invalid`
/// - `name`   → `[ERASED]`
/// - Other PII (password_hint, api_key) → cleared
/// - Marks `pii_erased_at` in users table
/// - Marks corresponding ErasureLog entry as completed
pub async fn execute_scheduled_erasures(pool: crate::db::DbPool) {
    let conn = match pool.get().await {
        Ok(c) => c,
        Err(e) => {
            error!("execute_scheduled_erasures: DB pool error: {e:?}");
            return;
        }
    };

    let pending = ErasureLog::find_pending_due(&conn).await;
    info!("[GDPR] Erasure job running: {} pending deletions", pending.len());

    for mut log in pending {
        // Find the user — they may have already been hard-deleted
        let user_opt = User::find_by_uuid(
            &crate::db::models::UserId::from(log.user_uuid.clone()),
            &conn,
        )
        .await;

        if let Some(mut user) = user_opt {
            // Anonymise PII
            user.email = format!("erased-{}@erased.invalid", user.uuid);
            user.name = "[ERASED]".to_string();
            user.password_hint = None;
            user.api_key = None;
            user.avatar_color = None;
            user.pii_erased_at = Some(Utc::now().naive_utc());

            if let Err(e) = user.save(&conn).await {
                error!("[GDPR] Failed to anonymise user {}: {e:?}", log.user_uuid);
                continue;
            }

            info!("[GDPR] Anonymised PII for user {}", log.user_uuid);
        } else {
            // User already deleted — still mark the log complete
            warn!("[GDPR] User {} not found; marking erasure log complete anyway", log.user_uuid);
        }

        // Mark erasure log complete
        log.mark_completed();
        if let Err(e) = log.save(&conn).await {
            error!("[GDPR] Failed to update erasure log {}: {e:?}", log.uuid);
        }
    }
}
